on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest
    steps:
      - name: connect and pull
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            git checkout ${{ secrets.DEPLOYMENT_BRANCH }}
            git pull
