on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and try to build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          cd backend
          yarn install --frozen-lockfile
          yarn test
          yarn build

  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: connect and pull
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            git checkout ${{ secrets.DEPLOYMENT_BRANCH }}
            git pull
            cd backend
            docker compose up -d --build backend
