name: Flutter CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get
        
      - name: Create .env file
        working-directory: ./app
        run: echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" > .env

      - name: Build APK
        working-directory: ./app
        run: flutter build apk

      - name: Send APK to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./app/build/app/outputs/flutter-apk/*"
          target: ${{ secrets.WORK_DIR }}/backend/site/
          strip_components: 5
          overwrite: true
