name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Create .env file
        run: cp .env.example .env
        
      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
